CREATE TABLE staff (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email citext NOT NULL UNIQUE,
  profile_picture TEXT,
  is_owner BOOLEAN NOT NULL DEFAULT FALSE,
  provider_id INTEGER NOT NULL REFERENCES providers(id) ON DELETE CASCADE
)